name: Auto Pass ✅

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  pass-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print github context
        env:
          GHC: ${{ toJson(github) }}
        run: echo $GHC

      - name: Long task
        run: sleep 30

      - name: Run a one time script
        run: exit 0
