# This is a basic workflow to help you get started with Actions

name: Repository Dispatch 2

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Triggers the workflow on push or pull request events but only for the "main" branch
  repository_dispatch:
    types: [upx-frontend-trunk-build, upx-frontend-pr-build]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  trunkBuild:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEW_VERSION: ${{ github.event.client_payload.build_name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Print build name
        run: echo ${{ github.event.client_payload.build_name }}

      - name: Set date as output
        id: date
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Print current GH user
        run: |
          gh auth status

      - name: Edit devenv and open PR
        run: |
          printf "\nBEFORE REPLACEMENT\n"
          cat devenv
          sed -i -e "s/^export UPX_FRONTEND_VERSION=.*/export UPX_FRONTEND_VERSION=${{ env.NEW_VERSION || steps.date.outputs.NOW }}/" devenv
          printf "\nAFTER REPLACEMENT\n"
          cat devenv
          printf "\nLIST FILES\n"
          ls -l
