# This is a basic workflow to help you get started with Actions

name: Repository Dispatch 2

# Controls when the workflow will run
on:
  push:
    branches: [main]

  # Triggers the workflow on push or pull request events but only for the "main" branch
  repository_dispatch:
    types: [upx-frontend-trunk-build, upx-frontend-pr-build]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  trunkBuild:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.UPX_TOKEN }}
      NEW_VERSION: ${{ github.event.client_payload.build_name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Print build name
        run: echo ${{ github.event.client_payload.build_name }}

      - name: Print current GH user
        run: |
          gh auth status
          ls -la

      - name: Edit devenv and open PR
        run: |
          VERSION=${{ env.NEW_VERSION || github.run_number }}
          BRANCH_NAME="automated-bump/upx-frontend-${VERSION}"

          printf "\nBEFORE REPLACEMENT\n"
          cat devenv
          sed -i -e "s/^export UPX_FRONTEND_VERSION=.*/export UPX_FRONTEND_VERSION=${VERSION}/" devenv
          printf "\nAFTER REPLACEMENT\n"
          cat devenv
          printf "\nLIST FILES\n"
          ls -l
          printf "\nLIST BRANCH\n"
          BRANCH=$(git branch --show-current)
          echo $BRANCH

          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'

          # gh auth setup-git
          git checkout -b ${BRANCH_NAME}

          git add devenv
          git commit -m "Bump upx-frontend to ${VERSION}"
          git push --set-upstream origin ${BRANCH_NAME}

          gh pr create \
          --title "Bump upx-frontend to ${VERSION}" \
          --body "This is an automated pull request created from a build pipeline owned by the upx team." \
          --head "$(git branch --show-current)"

      # - name: Sleep
      #   run: |
      #     sleep 60
