# This is a basic workflow to help you get started with Actions

name: Workflow Dispatch

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      new_version:
        type: string
        description: "New version of the UPX frontend artifacts"
        required: true
      source_event:
        type: string
        description: "Original event that triggered this workflow, used in PR body"
        required: false
      source_event_url:
        type: string
        description: "URL of original event, used in PR body"
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-inputs:
    runs-on: ubuntu-latest
    env:
      GITHUB_INPUTS: ${{ toJson(inputs) }}
      GITHUB_EV_INPUTS: ${{ toJson(github.event.inputs) }}
    steps:
      - run: |
          echo "Inputs: ${GITHUB_INPUTS}"
          echo "Event Inputs: ${GITHUB_EV_INPUTS}"
